---
- hosts: appserver
  user: root
  sudo: yes
  tasks:
    - name: install httpd
      yum: name=httpd state=installed
    - name: start the service
      service: name=httpd state=started
      register: result
    - debug: var=result
