---
- hosts: appserver
  user: root
  sudo: yes
  gather_facts: no 
  vars: 
    pkg: httpd
  tasks:
    - name: install httpd
      yum: name={{pkg}} state=installed
    - name: copy index.html
      copy: src=index.html dest=/var/www/html/index.html
      notify: start httpd service
  handlers:    
    - name: start httpd service
      service: name={{pkg}} state=started

